# Generated by Django 4.2.2 on 2023-06-25 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('pirce', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('description', models.CharField(max_length=100)),
                ('trainer', models.CharField(max_length=20)),
                ('trainerDescription', models.CharField(max_length=20)),
            ],
        ),
    ]
