# Generated by Django 4.2.2 on 2023-06-25 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_courses', '0002_rename_pirce_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='longdescription',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
