# Generated by Django 4.2.2 on 2023-06-26 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_courses', '0004_course_duration_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(default='حضوري', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
