# Generated by Django 4.2.2 on 2023-06-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_courses', '0005_course_discount_course_type_delete_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trainerGender',
            field=models.CharField(choices=[('1', 'حضوري'), ('2', 'الكتروني')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('1', 'حضوري'), ('2', 'الكتروني')], max_length=1),
        ),
    ]
