# Generated by Django 4.2.2 on 2023-06-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_courses', '0006_course_trainergender_alter_course_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='trainerGender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'انثى')], max_length=1),
        ),
    ]
